name: CI Pipeline
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Run sample build
        run: echo "CI Build Successful!"

  JDK-install:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v6
      - name: install jdk
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: build with maven
        run: |
          cd spring-boot-app
          mvn -B clean package
          echo "build sucessfull"

                
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v7.0.0
        with:
          args:
            -Dproject.settings=spring-boot-app/sonar-project.properties
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: SonarQube Quality Gate check
        id: sonarqube-quality-gate-check
        uses: sonarsource/sonarqube-quality-gate-action@master
        with:
          pollingTimeoutSec: 600
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: uplocal attificat
        uses: actions/upload-artifact@v6.0.0
        with:
          name: my-artifact
          path: spring-boot-app/target/*.jar

  build-and-push-image-to-dockerhub:
    needs: JDK-install
    runs-on: ubuntu-latest
    steps:
  
      - name: checkout
        uses: actions/checkout@v6
      - name: download Build arthifact
        uses: actions/download-artifact@v7.0.0
        with:
          name: my-artifact
          path: spring-boot-app/target/
      - name: login to docker
        uses: docker/login-action@v3.6.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build docker image 
        run: |
          cd spring-boot-app
          docker build -t springboot:${{ github.sha }} .


      - name: push docker image to dockerhub
        uses: docker/build-push-action@v6
        with:
          context: ./spring-boot-app/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/springboot:${{ github.sha }} 
        
  update-the-deployment-files-and-commit-back:
    needs: build-and-push-image-to-dockerhub
    runs-on: ubuntu-latest
    steps:
      - name: Update deployment image and push to repo
        run: |
          cd spring-boot-app-manifests
          sed -i "s|image:.*|image: ${{ secrets.DOCKERHUB_USERNAME }}/springboot:${{ github.sha }}|" deployment.yml    
          git config user.name "Ismail-Attar"
          git config user.email "ismailattar@gmail.com"
          git add deployment.yml
          git commit -m "updated deployment file with image tag"
          git push origin HEAD:main
          git push origin HEAD:argocd






      


      
